# Generated by Django 3.2.13 on 2022-06-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('contact_number', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('number_of_seats', models.SmallIntegerField()),
                ('service', models.CharField(max_length=6)),
                ('date', models.DateField()),
            ],
        ),
    ]
