# Generated by Django 3.2.13 on 2022-08-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_booking', '0002_auto_20220728_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerDetails',
        ),
    ]
