# Generated by Django 3.2.13 on 2022-08-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_booking', '0003_delete_customerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginformation',
            name='service',
            field=models.CharField(choices=[('Lunch', 'Lunch 13:00'), ('Dinner', 'Dinner 19:00')], max_length=6),
        ),
        migrations.AlterField(
            model_name='bookinginformation',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
