# Generated by Django 3.2.13 on 2022-08-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_booking', '0004_auto_20220803_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginformation',
            name='service',
            field=models.CharField(choices=[('Lunch (13:00)', 'Lunch 13:00'), ('Dinner (19:00)', 'Dinner 19:00')], max_length=14),
        ),
    ]
